import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    author: "Jim Corbett",
    badge: "",
    binding: "Hardcover",
    categoryName: ["Non-Fiction"],
    description: "",
    discount: Math.floor(Math.random() * 21) + 5,
    fastDelivery: true,
    featured: false,
    inStock: true,
    lang: "English",
    price: "212",
    productImg:
      "https://rukminim2.flixcart.com/image/612/612/kz5vwy80/book/8/k/c/my-india-original-imagb8ryjhgkshgm.jpeg?q=70",
    rating: Math.random().toFixed(1) * 4 + 1,
    title: "My India",
  },
  {
    _id: uuid(),
    author: "Stephen King",
    badge: "",
    binding: "Paperback",
    categoryName: ["Fiction"],
    description: "",
    discount: Math.floor(Math.random() * 21) + 5,
    fastDelivery: false,
    featured: false,
    inStock: true,
    lang: "English",
    price: "278",
    productImg:
      "https://rukminim2.flixcart.com/image/612/612/kfoapow0/book/4/9/4/rita-hayworth-and-shawshank-redemption-original-imafw2rydzkzeshb.jpeg?q=70",
    rating: Math.random().toFixed(1) * 4 + 1,
    title: "Rita Hayworth and Shawshank Redemption",
  },
  {
    _id: uuid(),
    author: "Jawaharlal Nehru",
    badge: "",
    binding: "Hardcover",
    categoryName: ["Non-Fiction"],
    description: "",
    discount: Math.floor(Math.random() * 21) + 5,
    fastDelivery: true,
    featured: false,
    inStock: true,
    lang: "English",
    price: "499",
    productImg:
      "https://rukminim2.flixcart.com/image/612/612/krp94sw0/book/b/g/p/the-discovery-of-india-original-imag5fwxqgpwe5gh.jpeg?q=70",
    rating: Math.random().toFixed(1) * 4 + 1,
    title: "The Discovery of India",
  },
  {
    _id: uuid(),
    author: "William Dalrymple",
    badge: "",
    binding: "Paperback",
    categoryName: ["Non-Fiction"],
    description: "",
    discount: Math.floor(Math.random() * 21) + 5,
    fastDelivery: true,
    featured: false,
    inStock: true,
    lang: "English",
    price: "799",
    productImg:
      "https://rukminim2.flixcart.com/image/612/612/kj0bp8w0-0/book/h/3/h/city-of-djinns-original-imafyzyruhbdddp9.jpeg?q=70",
    rating: Math.random().toFixed(1) * 4 + 1,
    title: "City of Djinns",
  },
  {
    _id: uuid(),
    author: "Fredrik Backman",
    badge: "Popular",
    binding: "Paperback",
    categoryName: ["Fiction", "Popular"],
    description: "",
    discount: Math.floor(Math.random() * 21) + 5,
    fastDelivery: true,
    featured: false,
    inStock: true,
    lang: "English",
    price: "215",
    productImg:
      "https://rukminim2.flixcart.com/image/612/612/kz7bcsw0/regionalbooks/n/i/8/a-man-called-ove-original-imagb9t3thsugbsg.jpeg?q=70",
    rating: Math.random().toFixed(1) * 4 + 1,
    title: "A Man Called Ove",
  },
  {
    _id: uuid(),
    author: "Suketu Mehta",
    badge: "",
    binding: "Paperback",
    categoryName: ["Non-Fiction"],
    description: "",
    discount: Math.floor(Math.random() * 21) + 5,
    fastDelivery: true,
    featured: false,
    inStock: true,
    lang: "English",
    price: "349",
    productImg:
      "https://rukminim2.flixcart.com/image/612/612/kk1h5e80/book/f/8/j/maximum-city-original-imafzgzye8ygfqjz.jpeg?q=70",
    rating: Math.random().toFixed(1) * 4 + 1,
    title: "Maximum City",
  },
  {
    _id: uuid(),
    author: "Shubhangi Swaroop",
    badge: "",
    binding: "Hardcover",
    categoryName: ["Fiction"],
    description: "",
    discount: Math.floor(Math.random() * 21) + 5,
    fastDelivery: true,
    featured: false,
    inStock: true,
    lang: "English",
    price: "323",
    productImg:
      "https://rukminim2.flixcart.com/image/612/612/k34rki80/book/7/4/1/latitudes-of-longing-original-imafmbwejtumzhz2.jpeg?q=70",
    rating: Math.random().toFixed(1) * 4 + 1,
    title: "Latitudes of Longing",
  },
  {
    _id: uuid(),
    author: "Ruskin Bond",
    badge: "Just In",
    binding: "Hardcover",
    categoryName: ["Fiction", "Just In"],
    description: "",
    discount: Math.floor(Math.random() * 21) + 5,
    fastDelivery: false,
    featured: false,
    inStock: true,
    lang: "English",
    price: "249",
    productImg:
      "https://rukminim2.flixcart.com/image/612/612/book/7/9/3/a-gathering-of-friends-original-imae5p4fy3wzs5kt.jpeg?q=70",
    rating: Math.random().toFixed(1) * 4 + 1,
    title: "A Gathering of Friends",
  },
  {
    _id: uuid(),
    author: "Walter Isaacson",
    badge: "",
    binding: "Hardcover",
    categoryName: ["Non-Fiction"],
    description: "",
    discount: Math.floor(Math.random() * 21) + 5,
    fastDelivery: false,
    featured: false,
    inStock: true,
    lang: "English",
    price: "599",
    productImg:
      "https://rukminim2.flixcart.com/image/612/612/km3s1ow0/regionalbooks/j/f/g/steve-jobs-the-exclusive-biography-paperback-original-imagf2u77ggte8cd.jpeg?q=70",
    rating: Math.random().toFixed(1) * 4 + 1,
    title: "Steve Jobs",
  },
  {
    _id: uuid(),
    author: "Ruskin Bond",
    badge: "",
    binding: "Hardcover",
    categoryName: ["Non-Fiction"],
    description: "",
    discount: Math.floor(Math.random() * 21) + 5,
    fastDelivery: true,
    featured: false,
    inStock: true,
    lang: "English",
    price: "399",
    productImg:
      "https://rukminim2.flixcart.com/image/612/612/kpydrbk0/book/i/l/y/lone-fox-dancing-original-imag43y6sayj3wug.jpeg?q=70",
    rating: Math.random().toFixed(1) * 4 + 1,
    title: "Lone Fox Dancing",
  },
  {
    _id: uuid(),
    author: "Toshikazu Kawaguchi",
    badge: "Popular",
    binding: "Paperback",
    categoryName: ["Fiction", "Popular"],
    description: "",
    discount: Math.floor(Math.random() * 21) + 5,
    fastDelivery: true,
    featured: false,
    inStock: true,
    lang: "English",
    price: "299",
    productImg:
      "https://rukminim2.flixcart.com/image/612/612/k0e66q80/book/5/8/1/before-the-coffee-gets-cold-original-imafk7gcgpapjytm.jpeg?q=70",
    rating: Math.random().toFixed(1) * 4 + 1,
    title: "Before the Coffee Gets Cold",
  },
  {
    _id: uuid(),
    author: "Stephen King",
    badge: "Just In",
    binding: "Hardcover",
    categoryName: ["Fiction", "Just In"],
    description: "",
    discount: Math.floor(Math.random() * 21) + 5,
    fastDelivery: true,
    featured: true,
    inStock: true,
    lang: "English",
    price: "650",
    productImg:
      "https://rukminim2.flixcart.com/image/612/612/kqb8pzk0/book/g/o/t/billy-summers-original-imag4c74n9trefpe.jpeg?q=70",
    rating: Math.random().toFixed(1) * 4 + 1,
    title: "Billy Summers",
  },
  {
    _id: uuid(),
    author: "Heinrich Harrer",
    badge: "",
    binding: "Paperback",
    categoryName: ["Non-Fiction"],
    description: "",
    discount: Math.floor(Math.random() * 21) + 5,
    fastDelivery: true,
    featured: false,
    inStock: false,
    lang: "English",
    price: "279",
    productImg:
      "https://rukminim2.flixcart.com/image/612/612/jpodaq80/book/0/7/7/seven-years-in-tibet-original-imafbuk2jtzmnnqy.jpeg?q=70",
    rating: Math.random().toFixed(1) * 4 + 1,
    title: "Seven Years in Tibet",
  },
  {
    _id: uuid(),
    author: "James Clear",
    badge: "Popular",
    binding: "Paperback",
    categoryName: ["Self-Help", "Popular", "Non-Fiction"],
    description: "",
    discount: Math.floor(Math.random() * 21) + 5,
    fastDelivery: true,
    featured: true,
    inStock: true,
    lang: "English",
    price: "378",
    productImg:
      "https://rukminim2.flixcart.com/image/612/612/kufuikw0/book/x/s/w/atomic-habits-original-imag7kbzg2fu8rjv.jpeg?q=70",
    rating: Math.random().toFixed(1) * 4 + 1,
    title: "Atomic Habits",
  },
  {
    _id: uuid(),
    author: "Morgan Housel",
    badge: "Just In",
    binding: "Paperback",
    categoryName: ["Self-Help", "Non-Fiction", "Just In"],
    description: "",
    discount: Math.floor(Math.random() * 21) + 5,
    fastDelivery: false,
    featured: false,
    inStock: true,
    lang: "English",
    price: "231",
    productImg:
      "https://rukminim2.flixcart.com/image/612/612/kjom6q80-0/regionalbooks/o/i/t/the-psychology-of-money-original-imafvb5vbgcczykj.jpeg?q=70",
    rating: Math.random().toFixed(1) * 4 + 1,
    title: "The Psychology of Money",
  },
  {
    _id: uuid(),
    author: "George Orwell",
    badge: "",
    binding: "Paperback",
    categoryName: ["Fiction"],
    description: "",
    discount: Math.floor(Math.random() * 21) + 5,
    fastDelivery: true,
    featured: false,
    inStock: false,
    lang: "Marathi",
    price: "149",
    productImg:
      "https://rukminim2.flixcart.com/image/612/612/book/4/4/4/1984-original-imadajyuan6zxbwd.jpeg?q=70",
    rating: Math.random().toFixed(1) * 4 + 1,
    title: "1984",
  },
  {
    _id: uuid(),
    author: "Ramchandra Guha",
    badge: "",
    binding: "Hardcover",
    categoryName: ["Non-Fiction"],
    description: "",
    discount: Math.floor(Math.random() * 21) + 5,
    fastDelivery: true,
    featured: false,
    inStock: true,
    lang: "English",
    price: "549",
    productImg:
      "https://rukminim2.flixcart.com/image/612/612/k6pd7680/book/9/9/3/india-after-gandhi-original-imafp3uzgydsxz9r.jpeg?q=70",
    rating: Math.random().toFixed(1) * 4 + 1,
    title: "India After Gandhi",
  },
];
